# Generated by Django 5.1 on 2024-08-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0001_initial'),
        ('core_user', '0002_user_avatar_user_bio_alter_user_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts_liked',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='core_post.post'),
        ),
    ]
